# Generated by Django 3.2.15 on 2022-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0002_participant_registration_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(
                max_length=150, unique=True, verbose_name="Adresse électronique"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="participant_type",
            field=models.CharField(
                choices=[
                    ("PARTICULIER", "Particulier"),
                    ("ELU", "Élu"),
                    ("ASSOCIATION", "Représentant(e) d'une association"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="postal_code",
            field=models.CharField(max_length=5, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="theme",
            field=models.CharField(
                choices=[
                    ("CLIMAT", "Climat"),
                    ("VIEILLISSEMENT", "Générations et vieillissement"),
                    ("SOUVERAINETE", "Souveraineté économique"),
                    ("TRAVAIL", "Futur du travail"),
                    ("SANTE", "Santé"),
                    ("EDUCATION", "Éducation"),
                    ("LOGEMENT", "Logement"),
                    ("JEUNESSE", "Jeunesse"),
                    ("NUMERIQUE", "Numérique"),
                ],
                max_length=14,
            ),
        ),
    ]
