# Generated by Django 3.2.15 on 2022-09-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_website', '0003_auto_20220919_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='sub',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='theme',
            field=models.CharField(choices=[('CLIMAT', 'Climat'), ('VIEILLISSEMENT', 'Générations et vieillissement'), ('SOUVERAINETE', 'Souveraineté économique'), ('TRAVAIL', 'Futur du travail'), ('SANTE', 'Santé'), ('EDUCATION', 'Éducation'), ('LOGEMENT', 'Logement'), ('JEUNESSE', 'Jeunesse'), ('NUMERIQUE', 'Numérique')], max_length=14),
        ),
    ]
