# Generated by Django 3.2.15 on 2022-09-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0007_auto_20220922_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="public_website.participant",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="theme",
            field=models.CharField(
                choices=[
                    ("CLIMAT", "Climat et biodiversité"),
                    ("VIEILLISSEMENT", "Générations et vieillissement"),
                    ("SOUVERAINETE", "Souveraineté économique"),
                    ("TRAVAIL", "Futur du travail"),
                    ("SANTE", "Santé"),
                    ("EDUCATION", "Éducation"),
                    ("LOGEMENT", "Logement"),
                    ("JEUNESSE", "Jeunesse"),
                    ("NUMERIQUE", "Numérique"),
                ],
                max_length=14,
            ),
        ),
    ]
