# Generated by Django 3.2.15 on 2022-09-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0010_alter_subscription_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="sante_participant_type",
            field=models.CharField(
                choices=[
                    ("USAGER", "Usager"),
                    ("PROSANTE", "Médecins, acteur ou actrice du secteur de la santé"),
                    (
                        "ASSOCIATION",
                        "Association ou entreprise ayant un lien avec la santé",
                    ),
                    ("ELU", "Elu(e) local"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
