# Generated by Django 3.2.15 on 2022-09-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0012_participant_education_participant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="education_city",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Ville, département ou région",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="sante_city",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Ville, département ou région",
            ),
        ),
    ]
