# Generated by Django 3.2.15 on 2022-09-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0013_auto_20220929_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="education_participant_type",
            field=models.CharField(
                choices=[
                    ("PARENT", "Parent d’élève"),
                    ("PROFESSEUR", "Professeur(e)"),
                    (
                        "ASSOCIATION",
                        "Association ou entreprise ayant un lien avec l’école",
                    ),
                    ("ELU", "Elu(e) local"),
                    ("MAIRE", "Maire ou président(e) d’exécutif"),
                    ("AUTRE", "Autre"),
                ],
                max_length=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="sante_participant_type",
            field=models.CharField(
                choices=[
                    ("USAGER", "Usager"),
                    ("PROSANTE", "Médecins, acteur ou actrice du secteur de la santé"),
                    (
                        "ASSOCIATION",
                        "Association ou entreprise ayant un lien avec la santé",
                    ),
                    ("ELU", "Elu(e) local"),
                    ("AUTRE", "Autre"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
