# Generated by Django 3.2.15 on 2022-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0014_auto_20220930_1146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="education_participant_type",
            field=models.CharField(
                choices=[
                    ("PARENT", "Parent d’élève"),
                    ("PROFESSEUR", "Enseignant(e)"),
                    (
                        "ASSOCIATION",
                        "Organisation ayant un lien avec l’établissement scolaire",
                    ),
                    ("ELU", "Elu(e)"),
                    ("AUTRE", "Autre"),
                ],
                max_length=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="sante_participant_type",
            field=models.CharField(
                choices=[
                    ("USAGER", "Patient"),
                    ("PROSANTE", "Personnel soignant"),
                    (
                        "ASSOCIATION",
                        "Organisation ayant un lien avec mon territoire de santé",
                    ),
                    ("ELU", "Elu(e) local"),
                    ("AUTRE", "Autre"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
