# Generated by Django 3.2.15 on 2022-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0015_auto_20220930_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="participant_type",
            field=models.CharField(
                choices=[
                    ("PARTICULIER", "Particulier"),
                    ("ELU", "Élu(e)"),
                    ("ASSOCIATION", "Représentant(e) d'un corps intermédiaire"),
                ],
                default="PARTICULIER",
                max_length=11,
            ),
        ),
    ]
