# Generated by Django 3.2.15 on 2022-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0016_alter_participant_participant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="education_participant_type",
            field=models.CharField(
                choices=[
                    ("PARENT", "Parent d’élève"),
                    ("PROFESSEUR", "Enseignant(e)"),
                    (
                        "ASSOCIATION",
                        "Organisation ayant un lien avec l’établissement scolaire",
                    ),
                    ("ELU", "Élu(e)"),
                    ("AUTRE", "Autre"),
                ],
                max_length=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="sante_participant_type",
            field=models.CharField(
                choices=[
                    ("USAGER", "Usager ou usagère (patient(e), accompagnant(e) ...)"),
                    ("PROSANTE", "Personnel soignant"),
                    (
                        "ASSOCIATION",
                        "Organisation ayant un lien avec mon territoire de santé",
                    ),
                    ("ELU", "Élu(e)"),
                    ("AUTRE", "Autre"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
