# Generated by Django 3.2.15 on 2022-09-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_dml_create_initial_surveys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="theme",
            field=models.CharField(
                choices=[
                    ("CLIMAT", "Climat et biodiversité"),
                    ("VIEILLISSEMENT", "Générations et vieillissement"),
                    ("SOUVERAINETE", "Souveraineté économique"),
                    ("TRAVAIL", "Futur du travail"),
                    ("SANTE", "Santé"),
                    ("EDUCATION", "Éducation"),
                    ("LOGEMENT", "Logement"),
                    ("JEUNESSE", "Jeunesse"),
                    ("NUMERIQUE", "Numérique"),
                ],
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveyparticipation",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="surveys.survey",
            ),
        ),
    ]
