# Generated by Django 3.2.15 on 2022-09-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_auto_20220924_1547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyquestion",
            name="rank",
        ),
    ]
