# Generated by Django 3.2.15 on 2022-09-28 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_alter_surveyquestion_answer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyanswer",
            name="survey_response_id",
            field=models.CharField(
                default="1234567891011121",
                max_length=22,
                validators=[django.core.validators.MinLengthValidator(16)],
                verbose_name="Identificateur de réponse au questionnaire",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="surveyanswer",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
