name: Compile SCSS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Copy empty .env.test to .env
        run: |
          cp .env.test .env
      - name: Compile SCSS
        run: |
          python manage.py compilescss
      - name: Add and commit changes
        uses: EndBug/add-and-commit@v9.1.0
        with:
          author_name: "InfraBetaGouv "
          author_email: "infra@beta.gouv.fr"
          message: "chore: compile scss"
